version: '3.8'
services:
  api:
    build: ./api
    env_file: ./api/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petshop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
